name: flutter_todoapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  hive: ^2.2.3  
  hive_flutter: ^1.1.0  
  cupertino_icons: ^1.0.8
  flutter_slidable: ^3.0.0
  flutter_slidable: ^3.0.0 
  # firebase_auth: ^4.17.4  # <-- keep this only if you plan to add login


  # cloud_firestore: ^4.15.0
  # firebase_auth: ^4.17.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
